version: '3'

services:
  anathadnode0:
    container_name: anathadnode0
    image: "anatha/core"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-anathad.log}
    volumes:
      - ./build:/anathad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  anathadnode1:
    container_name: anathadnode1
    image: "anatha/core"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-anathad.log}
    volumes:
      - ./build:/anathad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  anathadnode2:
    container_name: anathadnode2
    image: "anatha/core"
    environment:
      - ID=2
      - LOG=${LOG:-anathad.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/anathad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  anathadnode3:
    container_name: anathadnode3
    image: "anatha/core"
    environment:
      - ID=3
      - LOG=${LOG:-anathad.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/anathad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

  anathadnode4:
    container_name: anathadnode4
    image: "anatha/core"
    environment:
      - ID=4
      - LOG=${LOG:-anathad.log}
    ports:
      - "26665-26666:26656-26657"
    volumes:
      - ./build:/anathad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.6

  anathadnode5:
    container_name: anathadnode5
    image: "anatha/core"
    environment:
      - ID=5
      - LOG=${LOG:-anathad.log}
    ports:
      - "26667-26668:26656-26657"
    volumes:
      - ./build:/anathad:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.7

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: 192.168.10.0/16
